"""create risk profiles table

Revision ID: 39b1c6c6896c
Revises: 7e5fd4be7be4
Create Date: 2026-09-28 12:56:37.666527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b1c6c6896c'
down_revision: Union[str, Sequence[str], None] = '7e5fd4be7be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calculated_risk_score', sa.Float(), nullable=True),
    sa.Column('max_loss_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('investment_horizon_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_user_id'), 'risk_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_profiles_user_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    # ### end Alembic commands ###
